version: "3"
services: 
    web:
        build: .
        container_name: "webservice-flask"
        command: flask run --host 0.0.0.0
        ports:
          - "5000:5000"
        volumes:
          - .:/docker
        depends_on:
          - db
        links:
          - db
    db:
        image: mongo:4.2.6
        container_name: 'mongodb'
        volumes: 
          - ./mongo-volume:/data/db